### ISSUE TITLE
Address mobile issues on homepage

### ISSUE THREAD

**Issue by booherbg** [Asyncing-Ship/turtle_mountain#153]
- bubbles stacked
- navbar width

**Comment by JakeCr8Guru** [comment]
I did not do anything but this looks good already. The buttons stack on mobile and the navbar looks pretty good in my opinion.

**Comment by JakeCr8Guru** [comment]
This is a weird one.

**Comment by JakeCr8Guru** [comment]
I added more media queries using chakra ui

**Comment by JakeCr8Guru** [comment]
I have made things responsive
